export const officialAnswers = {
  1: "Over 2.00",
  2: "Heads",
  3: "New England",
  4: "Pass", 
  5: "Field Goal",
  6: "Seattle",
  7: "Even", 
  8: "Interception", 
  9: "Beer", 
  10: "Seattle",
  11: "Mike MacDonald",
  12: "Defense",
  13: "BAILE INOLVIDABLE",
  14: "No Hat",
  15: "Yes",
  16: "No", 
  17: "Yes", 
  18: "No",
  19: "Yes",
  20: "No",
  21: "No",
  22: "No",
  23: "Yes",
  24: "Yes", 
  25: "No",
  26: "2", 
  27: "Michelob Ultra",
  28: "Chips",
  29: "Yes",
  30: "Yellow",
  31: "Teammates",
  32: "Seattle"
};

export const officialMVP = "Kenneth Walker III";
